name: Build

on:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]  # Skip this workflow for tags as release.yml will handle it
  pull_request:
    branches: [ '*' ]

permissions:
  contents: read

# Cancel in-progress runs when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
          check-latest: true

      - name: Set VERSION env for snapshot
        run: |
          echo "VERSION=dev" >> $GITHUB_ENV

      - name: Run tests
        run: make test

      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: build --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}

